<?xml version="1.0"?>
<package format="3">
  <name>object_scanner_web</name>
  <version>0.1.0</version>
  <description>Flask controls and Three.js visualization for object_scanner.</description>
  <maintainer email="jess@example.com">jess</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>object_scanner</exec_depend>
  <exec_depend>object_scanner_interfaces</exec_depend>
  <exec_depend>python3-flask</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
